### PR TITLE
Introduce Docker image + ci/cd + cleanup

### PR DESCRIPTION
**Pull request by Macleykun**
This still need docs, but i wanted to check if your interested in this.
Would ya like to use github registery or dockerhub?

### CODE REVIEW

**Comment by Macleykun** [comment]
> Just curious as to why you need to delete the VSCode workspace? I can't merge this into master as it is.

I found it strange to have someone else’s vscode settings in the project
It seemed odd me, and decided to ignore and remove them, however if you prefer to keep those file in the project I’ll revert those files in this pr!

**Comment by Macleykun** [comment]
fixed it :)
Would ya like to use dockerhub or github registery?

**Comment by Adambean** [comment]
> I found it strange to have someone else’s vscode settings in the project It seemed odd me, and decided to ignore and remove them, however if you prefer to keep those file in the project I’ll revert those files in this pr!

The VSCode and Sublime workspace are project specific rather than user specific and are intentionally versioned.

These are legitimately used to recommend (but not enforce) extensions, and to enforce settings deemed important to the project. In the case of this project space, tab, and end of file line settings are defined to help the project comply with [PSR-1](https://www.php-fig.org/psr/psr-1) and [PSR-12](https://www.php-fig.org/psr/psr-12/). (Though they don't enforce every rule from those.)

**Comment by Macleykun** [comment]
> > I found it strange to have someone else’s vscode settings in the project It seemed odd me, and decided to ignore and remove them, however if you prefer to keep those file in the project I’ll revert those files in this pr!
> 
> The VSCode and Sublime workspace are project specific rather than user specific and are intentionally versioned.
> 
> These are legitimately used to recommend (but not enforce) extensions, and to enforce settings deemed important to the project. In the case of this project space, tab, and end of file line settings are defined to help the project comply with [PSR-1](https://www.php-fig.org/psr/psr-1) and [PSR-12](https://www.php-fig.org/psr/psr-12/). (Though they don't enforce every rule from those.)

Understood! Revert the git ignore aswell!

**Comment by Macleykun** [comment]
Heya, is the pr good for ya?

**Review by Adambean — COMMENTED** [review]
Looks legit.

**Comment by Adambean** [comment]
Thanks for that @Macleykun, merge accepted.

**Pull request merged**
